# Dependencies
# markdown: redcarpet
# pygments: true

# Permalinks
permalink: pretty

# Setup
title: Raheel Khan
tagline: "Software Developer"
description: "I write about my development experiences here"
url: http://raheelkhan.github.io

author:
  name: "Raheel Masood"
  url: https://github.com/raheelkhan

paginate: 5

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/raheelkhan/raheelkhan.github.io
